/**
 * Conceptual Bridge - Knowledge Runtime v1.0
 * Module: API Response Builder
 * 
 * Formats and validates runtime outputs from the random question selector into the 
 * standard API response payload structure.
 */

/**
 * Validates the runtime object input generated by the random question selector.
 * 
 * @param {Object} runtime - The runtime output object.
 * @returns {boolean} True if runtime object is valid, false otherwise.
 */
function isValidRuntime(runtime) {
    return Boolean(
        runtime &&
        typeof runtime === "object" &&
        !Array.isArray(runtime) &&
        runtime.success === true &&
        typeof runtime.subject === "string" &&
        typeof runtime.mode === "string" &&
        Array.isArray(runtime.sourceFiles) &&
        typeof runtime.totalSourceFiles === "number" &&
        typeof runtime.totalQuestions === "number" &&
        typeof runtime.generatedAt === "string" &&
        runtime.selectionMetadata &&
        typeof runtime.selectionMetadata === "object" &&
        !Array.isArray(runtime.selectionMetadata) &&
        Array.isArray(runtime.questions)
    );
}

/**
 * Converts a valid runtime object into the standard API response structure.
 * 
 * @param {Object} runtime - Runtime object returned from selectRandomQuestions.
 * @returns {{
 *   success: true,
 *   runtime: {
 *     subject: string,
 *     mode: string,
 *     sourceFiles: string[],
 *     totalSourceFiles: number,
 *     totalQuestions: number,
 *     generatedAt: string,
 *     selectionMetadata: {
 *       requested: number,
 *       available: number,
 *       algorithm: string,
 *       selectedAt: string
 *     }
 *   },
 *   questions: Array
 * } | {
 *   success: false,
 *   error: "INVALID_RUNTIME"
 * }} Structured API response payload or error indicator.
 */
export function buildApiResponse(runtime) {
    try {
        if (!isValidRuntime(runtime)) {
            return {
                success: false,
                error: "INVALID_RUNTIME"
            };
        }

        const { questions, success, ...runtimeMetadata } = runtime;

        return {
            success: true,
            runtime: runtimeMetadata,
            questions: questions
        };
    } catch {
        return {
            success: false,
            error: "INVALID_RUNTIME"
        };
    }
}
