/**
 * Conceptual Bridge - Knowledge Runtime v1.0
 * Module: GACA Anchor Runtime Adapter
 * 
 * Adapts normalized anchor data from anchorImporter.js into a structured,
 * validated runtime anchor object for the Runtime Engine.
 */

/**
 * Validates and converts a normalized anchor object into a structured runtime anchor.
 *
 * @param {Object} anchorData - Normalized anchor object generated by anchorImporter.js
 * @returns {{
 *   success: boolean,
 *   runtimeAnchor: {
 *     mode: "GACA",
 *     metadata: { title: string, titleTemplate: string, setNumber: string, tags: string, topic: string, subTopic: string, level: string },
 *     media: { english: string, bengali: string, pdfEnglish: string, pdfBengali: string },
 *     source: { testSource: string, outputFilename: string },
 *     extraMetadata: Record<string, string>
 *   } | null,
 *   warnings: string[],
 *   errors: string[]
 * }} Result containing runtime anchor structure and diagnostics.
 */
export function buildRuntimeGacaAnchor(anchorData) {
    const warnings = [];
    const errors = [];

    // 1. Validate Input Object
    if (!anchorData || typeof anchorData !== "object" || Array.isArray(anchorData)) {
        errors.push("Invalid input: Expected a normalized anchor object.");
        return { success: false, runtimeAnchor: null, warnings, errors };
    }

    // 2. Validate Required Mode
    const mode = (anchorData.mode || "").trim().toUpperCase();
    if (mode !== "GACA") {
        errors.push(`Invalid mode: Expected "GACA", received "${anchorData.mode || ""}".`);
        return { success: false, runtimeAnchor: null, warnings, errors };
    }

    // 3. Perform Runtime-Specific Validations
    const testSource = (anchorData.testSource || "").trim();
    if (!testSource) {
        errors.push("Missing required runtime property: testSource.");
    }

    if (!anchorData.title && !anchorData.titleTemplate) {
        warnings.push("Anchor missing both title and titleTemplate.");
    }

    if (errors.length > 0) {
        return { success: false, runtimeAnchor: null, warnings, errors };
    }

    // 4. Construct Structured Runtime Anchor
    const runtimeAnchor = {
        mode: "GACA",
        metadata: {
            title: anchorData.title || "",
            titleTemplate: anchorData.titleTemplate || "",
            setNumber: anchorData.setNumber || "",
            tags: anchorData.tags || "",
            topic: anchorData.topic || "",
            subTopic: anchorData.subTopic || "",
            level: anchorData.level || ""
        },
        media: {
            english: anchorData.english || "",
            bengali: anchorData.bengali || "",
            pdfEnglish: anchorData.pdfEnglish || "none",
            pdfBengali: anchorData.pdfBengali || "none"
        },
        source: {
            testSource: testSource,
            outputFilename: anchorData.outputFilename || ""
        },

        resolution: {
            testSource: testSource,
            topic: anchorData.topic || "",
            subTopic: anchorData.subTopic || "",
            level: anchorData.level || ""
        },
        extraMetadata: anchorData.extraMetadata && typeof anchorData.extraMetadata === "object"
            ? { ...anchorData.extraMetadata }
            : {}
    };

    return {
        success: true,
        runtimeAnchor,
        warnings,
        errors
    };
}
