/**
 * Conceptual Bridge - Knowledge Runtime v1.0
 * Module: Random Question Selector
 * 
 * Selects a random subset of questions from a question pool using the Fisher-Yates algorithm,
 * preserving original pool metadata and adding selection statistics.
 */

/**
 * Validates the question pool object structure.
 * 
 * @param {Object} pool - The question pool object.
 * @returns {boolean} True if pool object is valid, false otherwise.
 */
function isValidPool(pool) {
    return Boolean(
        pool &&
        typeof pool === "object" &&
        !Array.isArray(pool) &&
        Array.isArray(pool.questions) &&
        typeof pool.subject === "string" &&
        typeof pool.mode === "string" &&
        Array.isArray(pool.sourceFiles)
    );
}

/**
 * Selects a random subset of questions from a question pool without mutating the input pool.
 * 
 * @param {Object} pool - The question pool object generated by buildQuestionPool.
 * @param {number} count - The number of random questions requested.
 * @returns {{
 *   success: true,
 *   subject: string,
 *   mode: string,
 *   sourceFiles: string[],
 *   totalSourceFiles: number,
 *   totalQuestions: number,
 *   generatedAt: string,
 *   selectionMetadata: {
 *     requested: number,
 *     available: number,
 *     algorithm: "FISHER_YATES",
 *     selectedAt: string
 *   },
 *   questions: Array
 * } | {
 *   success: false,
 *   error: string
 * }} Result payload containing selected questions and metadata, or an error indicator.
 */
export function selectRandomQuestions(pool, count) {
    if (!isValidPool(pool)) {
        return {
            success: false,
            error: "INVALID_POOL"
        };
    }

    if (typeof count !== "number" || !Number.isInteger(count) || count <= 0) {
        return {
            success: false,
            error: "INVALID_COUNT"
        };
    }

    const available = pool.questions.length;

    if (available === 0) {
        return {
            success: false,
            error: "EMPTY_POOL"
        };
    }

    if (count > available) {
        return {
            success: false,
            error: "COUNT_EXCEEDS_POOL"
        };
    }

    // Shallow copy of question items to ensure zero mutation of input pool
    const questionsCopy = pool.questions.map(q => ({ ...q }));

    // Standard Fisher-Yates (Knuth) Shuffle
    for (let i = questionsCopy.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        const temp = questionsCopy[i];
        questionsCopy[i] = questionsCopy[j];
        questionsCopy[j] = temp;
    }

    // Slice the requested subset
    const selectedQuestions = questionsCopy.slice(0, count);

    return {
        success: true,
        subject: pool.subject,
        mode: pool.mode,
        sourceFiles: [...pool.sourceFiles],
        totalSourceFiles: pool.totalSourceFiles ?? pool.sourceFiles.length,
    
        totalQuestions: pool.totalQuestions,
        selectedQuestions: selectedQuestions.length,
    
        generatedAt: pool.generatedAt,
    
        selectionMetadata: {
            requested: count,
            available: available,
            algorithm: "FISHER_YATES",
            selectedAt: new Date().toISOString()
        },
    
        questions: selectedQuestions
    };
}
